---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-config
data:
  hazelcast.yaml: |
    hazelcast:
      map:
        default:
          backup-count: 0
          async-backup-count: 0
          eviction:
            eviction-policy: LRU
            max-size-policy: USED_HEAP_PERCENTAGE
            size: 70
      network:
        join:
          auto-detection:
            enabled: false
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-dns: hazelcast.my-namespace.svc.cluster.local

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  replicas: 1
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: cache
          image: hazelcast/hazelcast:4.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5701
              name: hz-server
            - containerPort: 9090
              name: metrics
          env:
            - name: "JAVA_OPTS"
              value: "-Dhazelcast.config=/etc/hazelcast/hazelcast.yaml -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=30 -XX:+ExitOnOutOfMemoryError"
            - name: "PROMETHEUS_PORT"
              value: "9090"
          volumeMounts:
            - name: hazelcast-config
              mountPath: /etc/hazelcast
          resources:
            requests:
              cpu: "7"
              memory: "20Gi"
      volumes:
        - name: hazelcast-config
          configMap:
            name: hazelcast-config

---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5701
      protocol: TCP
      name: hz-server
  selector:
    app: hazelcast
